import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar, NavbarData } from "@/src/widgets/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   <head>
        {/* ✅ this runs as early as possible and writes class directly to body */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  var theme = localStorage.getItem('theme');
                  var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  var finalTheme = theme || (prefersDark ? 'dark' : 'light');
                  document.write('<body class="${geistSans.variable} ${geistMono.variable} antialiased ' + finalTheme + '">');
                } catch (e) {
                  document.write('<body class="${geistSans.variable} ${geistMono.variable} antialiased light">');
                }
              })();
            `,
          }}
        />
      </head>
      <body
      suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar {...NavbarData} />
        {children}
        <svg xmlns="http://www.w3.org/2000/svg" className="hidden">
  <filter id="purplescale">
    <feColorMatrix
      type="matrix"
      values="
        0.4 0.2 0.6 0 0
        0.3 0.2 0.5 0 0
        0.5 0.3 0.7 0 0
        0   0   0   1 0
      "
    />
  </filter>
</svg>


      </body>

    </html>
  );
}
